apiVersion: apps/v1
kind: Deployment
metadata:
  name: lockate-jobs
  namespace: lockate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lockate-jobs
  template:
    metadata:
      labels:
        app: lockate-jobs
    spec:
      imagePullSecrets:
        - name: harbor-credentials
      containers:
        - name: jobs
          image: harbor.kubernetes.giuseppebosa.eu/lockate/lockate:latest
          imagePullPolicy: Always
          command: ["java", "-jar", "lockate.jar", "--spring.profiles.active=jobs"]
          env:
            - name: DB_URL
              value: "postgresql://cnpg-cluster-rw.lockate.svc.cluster.local:5432/lockate"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
            - name: REDIS_HOST
              value: valkey.lockate.svc.cluster.local
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: valkey-password
                  key: password
            - name: REQUIRE_API_KEY
              value: "true"
