apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harbor-certificate
  namespace: harbor
spec:
  dnsNames:
    - "harbor.kubernetes.giuseppebosa.eu"
  issuerRef:
    name: le-prod
    kind: ClusterIssuer
  secretName: harbor-certificate
